#!/bin/bash

ALSAMIXER_FREEZE__OPT="/opt/alsamixer-freeze"
ALSAMIXER_FREEZE__CONFIG_PATH="$ALSAMIXER_FREEZE__OPT/asound.state"
ALSAMIXER_FREEZE__BIN="alsactl.sh"
ALSAMIXER_FREEZE__SERVICE_NAME="alsamixer-freeze.service"

echo "Creating folder '$ALSAMIXER_FREEZE__OPT' if not exists"
mkdir -p $ALSAMIXER_FREEZE__OPT

if [ ! -f "$ALSAMIXER_FREEZE__CONFIG_PATH" ]; then
  echo "Storing your current configuration at '$ALSAMIXER_FREEZE__CONFIG_PATH'"
  alsactl -f $ALSAMIXER_FREEZE__CONFIG_PATH store
  chmod +x $ALSAMIXER_FREEZE__CONFIG_PATH
else
  echo "File '$ALSAMIXER_FREEZE__CONFIG_PATH' already exists"
fi

echo "Creating '$ALSAMIXER_FREEZE__SERVICE_NAME'"
cp "$PWD/$ALSAMIXER_FREEZE__BIN" "$ALSAMIXER_FREEZE__OPT/$ALSAMIXER_FREEZE__BIN"
chmod +x "$ALSAMIXER_FREEZE__OPT/$ALSAMIXER_FREEZE__BIN"

cp "$ALSAMIXER_FREEZE__SERVICE_NAME.template" $ALSAMIXER_FREEZE__SERVICE_NAME
sed -i "s|{{BINARY}}|$(echo "$ALSAMIXER_FREEZE__OPT/$ALSAMIXER_FREEZE__BIN")|g" $ALSAMIXER_FREEZE__SERVICE_NAME

mv $ALSAMIXER_FREEZE__SERVICE_NAME /etc/systemd/system/
systemctl daemon-reload
systemctl start $ALSAMIXER_FREEZE__SERVICE_NAME
systemctl enable $ALSAMIXER_FREEZE__SERVICE_NAME
